;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

include-file = ./colors.ini
include-file = ./modules.ini



[bar/main]
override-redirect = true
width = 94%
height = 32pt
radius = 0
fixed-center = true

offset-x = 3%
offset-y = 0.8%

dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt

padding-left = 1
padding-right = 2

module-margin = 1

separator = 
separator-foreground = ${colors.disabled}

font-0 = "Inconsolata:style=Bold:size=12;2"
font-1 = "Material Icons:size=14;4"
font-2 = "Material Icons Outlined:size=14;4"
font-3 = "Material Icons Round:size=14;4"
font-4 = "Material Icons Sharp:size=14;4"
font-5 = "Material Icons TwoTone:size=14;4"
font-6 = "M PLUS 1 Code:style=Bold:size=14;4"
font-7 = "3270 Nerd Font:style=Regular:size=11;4"
font-8 = "Unifont:style=Regular:size=14;4"

modules-left = menu xworkspaces 
modules-center = xwindow
modules-right =  mpd battery audio keyboard date systray powermenu 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
;
wm-restack = i3

