
[module/audio]
type = internal/pulseaudio


format-volume = <ramp-volume><label-volume>
format-volume-overline = ${colors.background}
format-volume-underline = ${colors.background}

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
format-muted = <label-muted>
format-muted-prefix = 
format-muted-prefix-background = ${colors.mantle}
format-muted-prefix-foreground = ${colors.red}
format-muted-prefix-padding = 1
format-muted-overline = ${colors.background}
format-muted-underline = ${colors.background}

; Available tokens:
;   %percentage% (default)
label-volume = %percentage%%
label-volume-background = ${colors.background-alt}
label-volume-padding = 1

; Available tokens:
;   %percentage% (default
label-muted = "Muted"
label-muted-foreground = ${colors.foreground}
label-muted-background = ${colors.background-alt}
label-muted-padding = 1

; Only applies if <ramp-volume> is used
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-background = ${colors.mantle}
ramp-volume-foreground = ${colors.green}
ramp-volume-padding = 1

; If defined, it will replace <ramp-volume> when
; headphones are plugged in to `headphone_control_numid`
; If undefined, <ramp-volume> will be used for both
; Only applies if <ramp-volume> is used
ramp-headphones-0 = 
ramp-headphones-background = ${colors.blue}
ramp-headphones-padding = 1


[module/menu]
type = custom/text
click-left = rofi -show

content = 
content-padding = 1
content-foreground = ${colors.color13}
content-background = ${colors.background}
content-underline = ${colors.background}
content-overline = ${colors.background}


[module/date]
type = internal/date
interval = 1

date = %I:%M %p
date-alt = %Y-%m-%d %H:%M:%S

format = <label>
format-prefix = 
format-prefix-padding = 1
format-prefix-background = ${colors.mantle}
format-prefix-foreground = ${colors.lavender}
format-prefix-underline = ${colors.background}
format-prefix-overline  = ${colors.background}
label = %date%
label-foreground = ${colors.foreground}
label-underline = ${colors.background}
label-overline = ${colors.background}
label-background = ${colors.background-alt}
label-padding = 1

[module/keyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format = <label-layout>

format-prefix = 
format-prefix-padding = 1
format-prefix-background = ${colors.mantle}
format-prefix-foreground = ${colors.sky}
format-prefix-underline = ${colors.background}
format-prefix-overline  = ${colors.background}


label-layout = %layout%
label-layout-foreground = ${colors.foreground}
label-layout-underline = ${colors.background}
label-layout-overline = ${colors.background}
label-layout-background = ${colors.background-alt}
label-layout-padding = 1


label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/separator]
type = custom/text
content = 
content-padding = 0
content-foreground = ${colors.foreground}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
;

[module/powermenu]
type = custom/text
click-left = ~/.config/rofi/powermenu.sh

label = %{F#f38ba8}%{F-}
label-foreground = ${colors.primary}


[module/xworkspaces]
type = internal/i3

ws-icon-0=1;一
ws-icon-1=2;二
ws-icon-2=3;三
ws-icon-3=4;四
ws-icon-4=5;五
ws-icon-5=6;六
ws-icon-6=7;七
ws-icon-7=8;八
ws-icon-8=9;九
ws-icon-9=10;十

label-focused = %icon%
label-focused-padding = 1
label-focused-background = ${colors.background}
label-focused-foreground = ${colors.color13}
label-focused-overline= ${colors.background}
label-focused-underline= ${colors.background}

label-unfocused = %icon%
label-unfocused-foreground = ${colors.foregorund}
label-unfocused-padding = 1


[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
label-foreground = ${colors.color14}

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/battery]
type = internal/battery

full-at = 99

battery = BAT0
adapter = ACAD
poll-interval = 2

format-discharging = <label-discharging>
format-discharging-prefix = 
format-discharging-prefix-padding = 1
format-discharging-prefix-background = ${colors.mantle}
format-discharging-prefix-foreground = ${colors.sapphire}
format-discharging-prefix-underline = ${colors.background}
format-discharging-prefix-overline  = ${colors.background}

label-discharging = %percentage%%
label-discharging-padding = 1
label-discharging-background = ${colors.background-alt}
label-discharging-underline = ${colors.background}
label-discharging-overline  = ${colors.background}

format-charging = <label-charging>
format-charging-prefix = 
format-charging-prefix-padding = 1
format-charging-prefix-background = ${colors.mantle}
format-charging-prefix-foreground = ${colors.green}
format-charging-prefix-underline = ${colors.background}
format-charging-prefix-overline  = ${colors.background}

label-charging = %percentage%%
label-charging-padding = 1
label-charging-background = ${colors.background-alt}
label-charging-underline = ${colors.background}
label-charging-overline  = ${colors.background}

[module/round-left]
type = custom/text
content = %{T7}%{T-}
content-foreground = #2b2f37

[module/round-right]
type = custom/text
content = %{T3}%{T-}
content-foreground = #2b2f37



[module/mpd]
type = internal/mpd

; Host where mpd is running (either ip or domain name)
; Can also be the full path to a unix socket where mpd is running.
host = 127.0.0.1
port = 6600
password = mysecretpassword

; Seconds to sleep between progressbar/song timer sync
; Default: 1
interval = 2
; Available tags:
;   <label-song> (default)
;   <label-time>
;   <bar-progress>
;   <toggle> - gets replaced with <icon-(pause|play)>
;   <toggle-stop> - gets replaced with <icon-(stop|play)>
;   <icon-random>
;   <icon-repeat>
;   <icon-repeatone> (deprecated)
;   <icon-single> - Toggle playing only a single song. Replaces <icon-repeatone>
;   <icon-consume>
;   <icon-prev>
;   <icon-stop>
;   <icon-play>
;   <icon-pause>
;   <icon-next>
;   <icon-seekb>
;   <icon-seekf>
format-online = <icon-prev> <icon-seekb> <icon-stop> <toggle> <icon-seekf> <icon-next>  <icon-repeat> <icon-random>  <bar-progress> <label-time>  <label-song>
;format-playing = ${self.format-online}
;format-paused = ${self.format-online}
;format-stopped = ${self.format-online}

; Available tags:
;   <label-offline>
; Default: ""
;format-offline = <label-offline>

; Available tokens:
;   %artist%
;   %album-artist%
;   %album%
;   %date%
;   %title%
; Default: %artist% - %title%
label-song = 𝄞 %artist% - %title%

; Available tokens:
;   %elapsed%
;   %total%
; Default: %elapsed% / %total%
;label-time = %elapsed% / %total%

; Available tokens:
;   None
label-offline = 🎜 mpd is offline

; Only applies if <icon-X> is used
icon-play = ⏵
icon-pause = ⏸
icon-stop = ⏹
icon-prev = ⏮
icon-next = ⏭
icon-seekb = ⏪
icon-seekf = ⏩
icon-random = 🔀
icon-repeat = 🔁
icon-repeatone = 🔂
icon-single = 🔂
icon-consume = ✀

; Used to display the state of random/repeat/repeatone/single
; Only applies if <icon-[random|repeat|repeatone|single]> is used
toggle-on-foreground = #ff
toggle-off-foreground = #55

; Only applies if <bar-progress> is used
bar-progress-width = 45
bar-progress-indicator = |
bar-progress-fill = ─
bar-progress-empty = ─
