[config]
reload_apps = true
scheme = "vibrant"

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true


[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = './templates/kitty.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.rofi]
input_path = '~/.config/matugen/templates/colors.rasi'
output_path = '~/.config/rofi/colors.rasi'
