[global]
frame_color = "#c8c093"
separator_color= frame

[urgency_low]
background = "#12120f"
foreground = "#c8c093"

[urgency_normal]
background = "#12120f"
foreground = "#c8c093"

[urgency_critical]
background = "#12120f"
foreground = "#c8c093"
frame_color = "#c4746e"
