#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五

setxkbmap -model pc105 -layout us,ru,ua -option "grp:alt_shift_toggle"

bspc config border_width         4
bspc config window_gap          18

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#232634"
bspc config focused_border_color "#4c4f69"
bspc rule -a pavucontrol state=floating focus=on rectangle=400x300+1250+50
#
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a steam state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zed state=floating
chwb2 -I '111111' -O 'cccccc' -i 1 -o 2 0x0400005 

xsetroot -cursor_name left_ptr
nm-applet &
jamesdsp -t &
flameshot &
bash $HOME/.config/polybar/launch.sh &
sh ~/.fehbg &
picom --config=$HOME/.config/picom/picom.conf &
