[general]
import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]
[font]
normal = { family = "Cozette", style = "Regular" }
size = 18

[window]
padding = { x = 24, y = 24 }

opacity = 1

# Colors (Kanagawa Wave)
# Source https//github.com/rebelot/kanagawa.nvim

